import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styled from 'styled-components'
const inter = Inter({ subsets: ["latin"] });
//import Navbar from "../components/Navbar";
import Footer from "../components/FooterFigma"
import  Navbar from "../components/NavbarFigma";
import StockMarket from "../components/StockMarket";
//TO RUn use npm run dev

const ParentContainer= styled.main`
  *{
    padding:0;
    //width: 100vw;
    flex-direction: row;
    }
`;

const Section1= styled.div`
    margin-top: 50px;
    margin-bottom: 50px;
    margin-left: 100px;
    margin-right: 100px;
    display: flex;
    justify-content: space-around;
`;
const Section2= styled.div`
    margin-top: 50px;
    margin-bottom: 50px;
    margin-left: 50px;
    margin-right: 50px;
    flex-direction: row;
`;

export default function Home() {
    return (
        <>
        <Head>
            <title>StockBlock Home</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        <StockMarket/>
        <Footer/>
        </>
    );
}

